# Generated by Django 4.1.4 on 2023-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_rename_email_registration_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mail_id',
            field=models.EmailField(max_length=100),
        ),
    ]
